#!/bin/sh
PHP_INI_SCAN_DIR='/var/www/u1894967/data/php-bin-php74-bx/malovichko.space:'
PHPRC='/var/www/u1894967/data/php-bin-php74-bx'
export PHP_INI_SCAN_DIR
export PHPRC
exec /opt/php/7.4-bx-optimized/bin/php-cgi
